services:
  nextjs:
    build: .
    container_name: portfolio
    restart: unless-stopped
    networks:
      - monitoring
    labels:
      - "traefik.enable=true"
      # Domaine principal
      - "traefik.http.routers.nextjs.rule=Host(`lou-tigroudja.com`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls=true"
      - "traefik.http.routers.nextjs.tls.certresolver=myresolver"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
      # Redirection www vers non-www
      - "traefik.http.routers.nextjs-www.rule=Host(`www.lou-tigroudja.com`)"
      - "traefik.http.routers.nextjs-www.entrypoints=websecure"
      - "traefik.http.routers.nextjs-www.tls.certresolver=myresolver"
      - "traefik.http.routers.nextjs-www.middlewares=www-redirect"
      # Métriques pour Prometheus
      - "traefik.http.middlewares.nextjs-metrics.prometheus.metrics.port=3000"
      - "traefik.http.middlewares.nextjs-metrics.prometheus.metrics.path=/metrics"

networks:
  monitoring:
    external: true